version: '3'

services:
    mongodb1:
        image: mongo
        restart: always
        container_name: mongodb1
        volumes:
            - ./data/mongodata1:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
            - ./mongo-setup/mongo-setup.js:/home/mongo-setup.js
        ports:
            - "27017:27017"
        command: ["--config","/etc/mongo.conf","--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

    mongodb2:
        image: mongo
        restart: always
        container_name: mongodb2
        volumes:
            - ./data/mongodata2:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
        ports:
            - "27018:27018"
        command: ["--config","/etc/mongo.conf","--replSet", "rs0", "--bind_ip_all", "--port", "27018"]

    mongodb3:
        image: mongo
        restart: always
        container_name: mongodb3
        volumes:
            - ./data/mongodata3:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
        ports:
            - "27019:27019"
        command: ["--config","/etc/mongo.conf","--replSet", "rs0", "--bind_ip_all", "--port", "27019"]

volumes:
    mongodata1:
    mongodata2:
    mongodata3:
