version: '3'

services:
    mongodb1:
        image: mongo
        restart: always
        container_name: mongodb1
        volumes:
            - ./data/mongodata1:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
        expose:
            - "27017"
        ports:
            - "27017:27017"
        command: mongod --config /etc/mongo.conf

    mongodb2:
        image: mongo
        restart: always
        container_name: mongodb2
        volumes:
            - ./data/mongodata2:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
        expose:
            - "27017"
        ports:
            - "27018:27017"
        command: mongod --config /etc/mongo.conf

    mongodb3:
        image: mongo
        restart: always
        container_name: mongodb3
        volumes:
            - ./data/mongodata3:/data/db
            - ./mongo-conf/mongo.conf:/etc/mongo.conf
        expose:
            - "27017"
        ports:
            - "27019:27017"
        command: mongod --config /etc/mongo.conf

    mongosetup:
        image: "mongo-setup"
        build: "./mongo-setup"
        container_name: "mongosetup"
        depends_on:
            - mongodb1
        volumes:
            - ./data/mongostatus:/data/
    

#volumes:
#    mongodata1:
#    mongodata2:
#    mongodata3:
#    mongostatus:
